!RUNGE-KUTTA METHOD
!PROBLEM::Given dy/dx=y-x,y(0)=2.Find y(0.1) and y(0.2) using second order Runge-Kutta method

PROGRAM RUNGE_KUTTA_2ND_ORDER
 IMPLICIT NONE
 
 INTEGER::I,J,N,OK
 REAL::X0,Y0,H,XF,F
 
 REAL,ALLOCATABLE::X(:),Y(:)
PRINT*,"ENTER THE INITIAL VALUE OF X AND Y"
 READ*,X0,Y0
PRINT*,"ENTER THE DIVISION VALUE I.E H"
 READ*,H
PRINT*,"ENTER THE VALUE OF X WHERE THE SOLUTION BE FINDING"
 READ*,XF

N= (XF-X0)/H
ALLOCATE(X(N+1),Y(N+1),STAT=OK)
X(1)=X0
Y(1)=Y0
DO I=1,N+1
 X(I+1) = X(I)+H
 Y(I+1) =Y(I)+0.5*H* (F(X(I),Y(I)) + F( X(I)+H , Y(I)+H*F(X(I),Y(I)) ))
END DO

PRINT*,"X=",X(N+1),"Y=",Y(N+1)

END PROGRAM RUNGE_KUTTA_2ND_ORDER

FUNCTION F(X,Y)
 IMPLICIT NONE
 REAL,INTENT(IN)::X,Y
 REAL :: F
 F= Y-X
END FUNCTION F
